### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by palamosteliaro** [ivaniskandar/shouko#3]
Rooted 5 ii on stock Android 11 rom. Provided root access and accessibility services. Tried assigning an app and media buttons, none of them is working.

**Comment by ivaniskandar** [comment]
You probably have the new assistant UI the one with glowing bar at the bottom. If you do then please wait for the next update.

**Comment by ivaniskandar** [comment]
Fixed by 4e168094f547250a8a7f45748d29c0ae3161e2f4. You can reopen this if you have the same issue with next update.

**Comment by ilmatematico** [comment]
Can you please update the provided pre-built apk in the release? I got the same problem and wish I could test without building the app by myself.

Thanks :)

**Comment by palamosteliaro** [comment]
> Can you please update the provided pre-built apk in the release? I got the same problem and wish I could test without building the app by myself.
> 
> Thanks :)
I also don't understand how is it "fixed" when the apk hasn't been updated since initial release...

**Comment by ilmatematico** [comment]
@ivaniskandar appreciated the new APK

for me still doesn't work, BUT I'm on Android 10
